version: "3.4"

services:

    sqldata:
       image: mcr.microsoft.com/mssql/server:2019-latest 

    catalog-api:
      image: ${REGISTRY:-rockstodons}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
      build:
        context: .
        dockerfile: Rockstodons-Backend\Services/Catalog.API/Dockerfile
      depends_on:
      - sqldata